# from pymongo import MongoClient
# client = MongoClient('localhost', 27017)
# db = client.dbsparta
#
# # 코딩 시작
# doc = { 'name' : 'bobby', 'age' : 21 }
# db.users.insert_one(doc)
import pymongo
from pymongo import MongoClient

ip ='mongodb://antitest:anti1234test@54.180.85.88'
port = 27017

client = pymongo.MongoClient('localhost', port)
db = client.anti


def insert():
    db.poster.delete_many({})
    db.wannabe.delete_many({})
    db.story.delete_many({})
    wordlist = [
        {"word": "Loving", "path": "../static/mapping/Loving.png"},
        {"word": "Dear", "path": "../static/mapping/Loving.png"},
        {"word": "Tender", "path": "../static/mapping/Loving.png"},
        {"word": "Fond", "path": "../static/mapping/Loving.png"},
        {"word": "Doting", "path": "../static/mapping/Loving.png"},
        {"word": "Lovely", "path": "../static/mapping/Loving.png"},
        {"word": "Classy", "path": "../static/mapping/Classy.png"},
        {"word": "High class", "path": "../static/mapping/Classy.png"},
        {"word": "Superior","path":"../static/mapping/Classy.png"},
        {"word": "Upmarket", "path": "../static/mapping/Classy.png"},
        {"word": "Stylish", "path": "../static/mapping/Classy.png"},
	    {"word": "Friendly", "path": "../static/mapping/Friendly.png"},
        {"word": "Neighbourly", "path": "../static/mapping/Friendly.png"},
        {"word": "Helpful", "path": "../static/mapping/Friendly.png"},
        {"word": "Amiable", "path": "../static/mapping/Friendly.png"},
        {"word": "Sympathetic", "path": "../static/mapping/Friendly.png"},
        {"word": "Progressive", "path": "../static/mapping/Progressive.png"},
        {"word": "Liberal", "path": "../static/mapping/Progressive.png"},
        {"word": "Advanced", "path": "../static/mapping/Progressive.png"},
        {"word": "Revolutionary","path":"../static/mapping/Progressive.png"},
        {"word": "Avant garde", "path": "../static/mapping/Progressive.png"},
        {"word": "Sporty", "path": "../static/mapping/Sporty.png"},
        {"word": "Athletic", "path": "../static/mapping/Sporty.png"},
        {"word": "Outdoor", "path": "../static/mapping/Sporty.png"},
        {"word": "Energetic", "path": "../static/mapping/Sporty.png"},
        {"word": "Peaceful", "path": "../static/mapping/Peaceful.png"},
        {"word": "At peace", "path": "../static/mapping/Peaceful.png"},
        {"word": "Harmonious", "path": "../static/mapping/Peaceful.png"},
        {"word": "Amicable", "path": "../static/mapping/Peaceful.png"},
        {"word": "Hostile", "path": "../static/mapping/Peaceful.png"},
        {"word": "Rich","path":"../static/mapping/Rich.png"},
        {"word": "Affluent", "path": "../static/mapping/Rich.png"},
        {"word": "Prosperous", "path": "../static/mapping/Rich.png"},
	    {"word": "Moneyed", "path": "../static/mapping/Rich.png"},
        {"word": "Wealthy", "path": "../static/mapping/Rich.png"},
        {"word": "Loaded", "path": "../static/mapping/Rich.png"},
        {"word": "Sweet", "path": "../static/mapping/Sweet.png"},
        {"word": "Sugary", "path": "../static/mapping/Sweet.png"},
        {"word": "Icky", "path": "../static/mapping/Sweet.png"},
        {"word": "Cloying", "path": "../static/mapping/Sweet.png"},
        {"word": "Hip", "path": "../static/mapping/Hip.png"},
        {"word": "Hipper","path":"../static/mapping/Hip.png"},
        {"word": "Hippest", "path": "../static/mapping/Hip.png"},
        {"word": "Great", "path": "../static/mapping/Great.png"},
        {"word": "Large", "path": "../static/mapping/Great.png"},
        {"word": "Big", "path": "../static/mapping/Great.png"},
        {"word": "Huge", "path": "../static/mapping/Great.png"},
        {"word": "Enormous", "path": "../static/mapping/Great.png"},
        {"word": "Young", "path": "../static/mapping/Young.png"},
        {"word": "Immature", "path": "../static/mapping/Young.png"},
        {"word": "Youthful", "path": "../static/mapping/Young.png"},
        {"word": "Little","path":"../static/mapping/Young.png"},
        {"word": "Junior", "path": "../static/mapping/Young.png"},
        {"word": "Infant", "path": "../static/mapping/Young.png"},
	    {"word": "Strong", "path": "../static/mapping/Strong.png"},
        {"word": "Muscular", "path": "../static/mapping/Strong.png"},
        {"word": "Hardy", "path": "../static/mapping/Strong.png"},
        {"word": "Sturdy", "path": "../static/mapping/Strong.png"},
        {"word": "Burly", "path": "../static/mapping/Strong.png"},
        {"word": "Strapping", "path": "../static/mapping/Strong.png"},
        {"word": "Faithful", "path": "../static/mapping/Faithful.png"},
        {"word": "Committed", "path": "../static/mapping/Faithful.png"},
        {"word": "Constant","path":"../static/mapping/Faithful.png"},
        {"word": "Dedicated", "path": "../static/mapping/Faithful.png"},
        {"word": "Reliable", "path": "../static/mapping/Faithful.png"},
        {"word": "Staunch", "path": "../static/mapping/Faithful.png"},
        {"word": "Funny", "path": "../static/mapping/Funny.png"},
        {"word": "Humorous", "path": "../static/mapping/Funny.png"},
        {"word": "Amusing", "path": "../static/mapping/Funny.png"},
        {"word": "Comic", "path": "../static/mapping/Funny.png"},
        {"word": "Hilarious", "path": "../static/mapping/Funny.png"},
        {"word": "Riotous", "path": "../static/mapping/Funny.png"},
        {"word": "Passionate", "path": "../static/mapping/Passionate.png"},
        {"word": "Eager","path":"../static/mapping/Passionate.png"},
        {"word": "Intense", "path": "../static/mapping/Passionate.png"},
        {"word": "Ardent", "path": "../static/mapping/Passionate.png"},
	    {"word": "Fervent", "path": "../static/mapping/Passionate.png"},
        {"word": "Fair", "path": "../static/mapping/Fair.png"},
        {"word": "Unbiased", "path": "../static/mapping/Fair.png"},
        {"word": "Impartial", "path": "../static/mapping/Fair.png"},
        {"word": "Just", "path": "../static/mapping/Fair.png"},
        {"word": "Reasonable", "path": "../static/mapping/Fair.png"},
        {"word": "Proper", "path": "../static/mapping/Fair.png"},
        {"word": "Cool", "path": "../static/mapping/Cool.png"},
        {"word": "Cold","path":"../static/mapping/Cool.png"},
        {"word": "Chilly", "path": "../static/mapping/Cool.png"},
        {"word": "Nippy", "path": "../static/mapping/Cool.png"},
        {"word": "Unconstrained","path":"../static/mapping/Unconstrained.png"},
        {"word": "Unaffected", "path": "../static/mapping/Unaffected.png"},
        {"word": "Clever", "path": "../static/mapping/Clever.png"},
	    {"word": "Intelligent", "path": "../static/mapping/Clever.png"},
        {"word": "Gifted", "path": "../static/mapping/Clever.png"},
        {"word": "Bright", "path": "../static/mapping/Clever.png"},
        {"word": "Traveling", "path": "../static/mapping/Traveling.png"},
        {"word": "Global", "path": "../static/mapping/Global.png"},
        {"word": "Worldwide", "path": "../static/mapping/Global.png"},
        {"word": "World", "path": "../static/mapping/Global.png"},
        {"word": "International", "path": "../static/mapping/Global.png"},
        {"word": "Universal","path":"../static/mapping/Global.png"},
        {"word": "Healthy", "path": "../static/mapping/Healthy.png"},
        {"word": "Well", "path": "../static/mapping/Healthy.png"},
        {"word": "Git","path":"../static/mapping/Healthy.png"},
        {"word": "In good shape", "path": "../static/mapping/Healthy.png"},
        {"word": "Witty", "path": "../static/mapping/Witty.png"},
	    {"word": "Dull", "path": "../static/mapping/Witty.png"},
        {"word": "Droll", "path": "../static/mapping/Witty.png"},
        {"word": "Whimsical", "path": "../static/mapping/Witty.png"},
        {"word": "Sparkling", "path": "../static/mapping/Witty.png"},
        {"word": "Be Loved", "path": "../static/mapping/Be-Loved.png"},
        {"word": "Valued", "path": "../static/mapping/Be-Loved.png"},
        {"word": "Prized", "path": "../static/mapping/Be-Loved.png"},
        {"word": "Precious", "path": "../static/mapping/Be-Loved.png"},
        {"word": "Darling","path":"../static/mapping/Be-Loved.png"},
        {"word": "Treasured", "path": "../static/mapping/Be-Loved.png"},
        {"word": "Calm", "path": "../static/mapping/Calm.png"},
        {"word": "Sedate", "path": "../static/mapping/Calm.png"},
        {"word": "Self possessed", "path": "../static/mapping/Calm.png"},
        {"word": "Dispassionate", "path": "../static/mapping/Calm.png"},
        {"word": "Famous", "path": "../static/mapping/Famous.png"},
        {"word": "Celebrated", "path": "../static/mapping/Famous.png"},
        {"word": "Interesting", "path": "../static/mapping/Interesting.png"},
        {"word": "Appealing", "path": "../static/mapping/Interesting.png"},
        {"word": "Gripping","path":"../static/mapping/Interesting.png"},
        {"word": "Inspirational", "path": "../static/mapping/Inspirational.png"},
        {"word": "Tough", "path": "../static/mapping/Tough.png"},
	    {"word": "Stout", "path": "../static/mapping/Tough.png"},
        {"word": "Vigorous", "path": "../static/mapping/Tough.png"},
        {"word": "Seasoned", "path": "../static/mapping/Tough.png"},
        {"word": "Cute", "path": "../static/mapping/Cute.png"},
        {"word": "Lovable", "path": "../static/mapping/Cute.png"},
        {"word": "Benevolent", "path": "../static/mapping/Benevolent.png"},
        {"word": "Kindly", "path": "../static/mapping/Benevolent.png"},
        {"word": "Generous", "path": "../static/mapping/Benevolent.png"},
        {"word": "Big hearted","path":"../static/mapping/Benevolent.png"},
        {"word": "Munificent", "path": "../static/mapping/Benevolent.png"},
        {"word": "Unselfish", "path": "../static/mapping/Benevolent.png"},
        {"word": "Ungrudging", "path": "../static/mapping/Benevolent.png"},
        {"word": "Joyful", "path": "../static/mapping/Joyful.png"},
        {"word": "Joyous", "path": "../static/mapping/Joyful.png"},
        {"word": "Well known", "path": "../static/mapping/Well-known.png"},
        {"word": "Noted", "path": "../static/mapping/Well-known.png"},
        {"word": "Prominent", "path": "../static/mapping/Well-known.png"},
        {"word": "Renowned", "path": "../static/mapping/Well-known.png"},
        {"word": "Christian", "path": "../static/mapping/Christian.png"},
        {"word": "Natural","path":"../static/mapping/Natural.png"},
        {"word": "Ordinary", "path": "../static/mapping/Natural.png"},
        {"word": "Typical", "path": "../static/mapping/Natural.png"},
	    {"word": "Everyday", "path": "../static/mapping/Natural.png"},
        {"word": "Smart", "path": "../static/mapping/Smart.png"},
        {"word": "Chic", "path": "../static/mapping/Smart.png"},
        {"word": "Neat", "path": "../static/mapping/Smart.png"},
        {"word": "Snappy", "path": "../static/mapping/Smart.png"},
        {"word": "Natty", "path": "../static/mapping/Smart.png"},
        {"word": "Scruffy", "path": "../static/mapping/Smart.png"},
        {"word": "Knowledgeable", "path": "../static/mapping/Knowledgeable.png"},
        {"word": "Learned","path":"../static/mapping/Knowledgeable.png"},
        {"word": "Educated", "path": "../static/mapping/Knowledgeable.png"},
        {"word": "Conversant", "path": "../static/mapping/Knowledgeable.png"},
        {"word": "Beautiful", "path": "../static/mapping/Beautiful.png"},
        {"word": "Pretty", "path": "../static/mapping/Beautiful.png"},
        {"word": "Pleasant", "path": "../static/mapping/Beautiful.png"},
        {"word": "Fetching", "path": "../static/mapping/Beautiful.png"},
        {"word": "Cheerful", "path": "../static/mapping/Cheerful.png"},
        {"word": "Optimistic", "path": "../static/mapping/Cheerful.png"},
        {"word": "Enthusiastic", "path": "../static/mapping/Cheerful.png"},
        {"word": "Splendid","path":"../static/mapping/Splendid.png"},
        {"word": "Marvellous", "path": "../static/mapping/Splendid.png"},
        {"word": "Unattached", "path": "../static/mapping/Unattached.png"},
	    {"word": "Single", "path": "../static/mapping/Unattached.png"},
        {"word": "Unmarried", "path": "../static/mapping/Unattached.png"},
        {"word": "Brave", "path": "../static/mapping/Brave.png"},
        {"word": "Courageous", "path": "../static/mapping/Brave.png"},
        {"word": "Heroic", "path": "../static/mapping/Brave.png"},
        {"word": "Modest", "path": "../static/mapping/Modest.png"},
        {"word": "Moderate", "path": "../static/mapping/Modest.png"},
        {"word": "Considerate", "path": "../static/mapping/Considerate.png"},
        {"word": "Thoughtful","path":"../static/mapping/Considerate.png"},
        {"word": "Concerned", "path": "../static/mapping/Considerate.png"},
        {"word": "Mindful", "path": "../static/mapping/Considerate.png"},
        {"word": "Caring", "path": "../static/mapping/Considerate.png"},
        {"word": "Polite", "path": "../static/mapping/Considerate.png"},
        {"word": "Respectful", "path": "../static/mapping/Respectful.png"},
        {"word": "Reverent", "path": "../static/mapping/Respectful.png"},
        {"word": "Humble", "path": "../static/mapping/Respectful.png"},
        {"word": "Dutiful", "path": "../static/mapping/Respectful.png"},
        {"word": "Independent", "path": "../static/mapping/Independent.png"},
        {"word": "Separate", "path": "../static/mapping/Independent.png"},
        {"word": "Uncontrolled","path":"../static/mapping/Independent.png"},
        {"word": "Unconstrained", "path": "../static/mapping/Independent.png"},
        {"word": "Radical", "path": "../static/mapping/Radical.png"},
	    {"word": "Extreme", "path": "../static/mapping/Radical.png"},
        {"word": "Complete", "path": "../static/mapping/Radical.png"},
        {"word": "Entire", "path": "../static/mapping/Radical.png"},
        {"word": "Weeping", "path": "../static/mapping/Radical.png"},
        {"word": "Thorough", "path": "../static/mapping/Radical.png"},
        {"word": "Drastic", "path": "../static/mapping/Radical.png"},
        {"word": "Bold", "path": "../static/mapping/Bold.png"},
        {"word": "Fearless", "path": "../static/mapping/Bold.png"},
        {"word": "Enterprising","path":"../static/mapping/Bold.png"},
        {"word": "Courageous", "path": "../static/mapping/Bold.png"},
        {"word": "Lofty","path":"../static/mapping/Dignified.png"},
        {"word": "Noble", "path": "../static/mapping/Dignified.png"},
        {"word": "Courtly", "path": "../static/mapping/Dignified.png"},
	    {"word": "Majestic", "path": "../static/mapping/Dignified.png"},
        {"word": "Kingly", "path": "../static/mapping/Dignified.png"},
        {"word": "Proud", "path": "../static/mapping/Dignified.png"},
        {"word": "Grand", "path": "../static/mapping/Dignified.png"},
        {"word": "Brainy", "path": "../static/mapping/Brainy.png"},
        {"word": "Erudite", "path": "../static/mapping/Brainy.png"},
        {"word": "Highbrow", "path": "../static/mapping/Brainy.png"},
        {"word": "Academic", "path": "../static/mapping/Brainy.png"},
        {"word": "Cultured","path":"../static/mapping/Brainy.png"},
        {"word": "Scholarly", "path": "../static/mapping/Brainy.png"},
        {"word": "Communicative", "path": "../static/mapping/Communicative.png"},
        {"word": "Impressionable","path":"../static/mapping/Communicative.png"},
        {"word": "Sensitive", "path": "../static/mapping/Communicative.png"},
        {"word": "Open minded", "path": "../static/mapping/Open-minded.png"},
	    {"word": "Balanced", "path": "../static/mapping/Open-minded.png"},
        {"word": "Objective", "path": "../static/mapping/Open-minded.png"},
        {"word": "Tolerant", "path": "../static/mapping/Open-minded.png"},
        {"word": "Receptive", "path": "../static/mapping/Open-minded.png"},
        {"word": "Free", "path": "../static/mapping/Free.png"},
        {"word": "Lots of hair", "path": "../static/mapping/Lots-of-hair.png"},
        {"word": "Strong Minded", "path": "../static/mapping/Strong-Minded.png"},
        {"word": "Firm", "path": "../static/mapping/Strong-Minded.png"},
        {"word": "Resolute","path":"../static/mapping/Strong-Minded.png"},
        {"word": "Purposeful", "path": "../static/mapping/Strong-Minded.png"},
        {"word": "Fearless", "path": "../static/mapping/Strong-Minded.png"},
        {"word": "Warm", "path": "../static/mapping/Warm.png"},
        {"word": "Balmy","path":"../static/mapping/Warm.png"},
        {"word": "Mild", "path": "../static/mapping/Warm.png"},
        {"word": "Temperate", "path": "../static/mapping/Warm.png"},
	    {"word": "Happy", "path": "../static/mapping/Happy.png"},
        {"word": "Thrilled", "path": "../static/mapping/Happy.png"},
        {"word": "Pleased", "path": "../static/mapping/Happy.png"},
        {"word": "Delighted", "path": "../static/mapping/Happy.png"},
        {"word": "Fine", "path": "../static/mapping/Happy.png"},
        {"word": "Pleasant", "path": "../static/mapping/Happy.png"},
        {"word": "Relaxed", "path": "../static/mapping/Relaxed.png"},
        {"word": "Relaxing", "path": "../static/mapping/Relaxed.png"},
        {"word": "Satified","path":"../static/mapping/Relaxed.png"},
        {"word": "Relieve", "path": "../static/mapping/Relaxed.png"},
        {"word": "Relieved", "path": "../static/mapping/Relaxed.png"},
        {"word": "Artistic", "path": "../static/mapping/Artistic.png"},
        {"word": "Eloquent","path":"../static/mapping/Artistic.png"},
        {"word": "Creative", "path": "../static/mapping/Artistic.png"},
        {"word": "Refined", "path": "../static/mapping/Artistic.png"}
   

    ]
    db.wannabe.insert_many(wordlist)
    stories = [
        {"story": "1너무재밋다"},{"story":"2할무니"}, {"story":"3부자되세요"},{"story":"4부자되세요를레이히리릴요요오로로리리ㅣ리릴리헤헤헷"}
    ]
    db.story.insert_many(stories)
    


insert()



